apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-sample-app
  template:
    metadata:
      labels:
        app: my-sample-app
    spec:
      containers:
        - name: my-sample-app
          image: your-dockerhub-username/my-sample-app:latest
          ports:
            - containerPort: 80
